### ISSUE TITLE
How are you using Reasons for fallback ?

### ISSUE THREAD

**Issue by DotDebian** [jamezrin/PlayerBalancer#11]
Hello Jamezrin,

I tried setting the fallback reasons to `reasons=[/Sanction/, /Raison/]` but it's still not working.
My exact reason is:
> §6§lExotic§e§lFight §8§m  §r §c§lSanction
> §7
> §6§l§r§cExclusion
> §cRaison §8» §7t
> §7

It contains both strings, and the mode is set to blacklist.
Can you help me setting this ? It could help others too.

EDIT: Fixed it by using `reasons=["*Sanction*"]`

**Comment by jamezrin** [comment]
Great :) I was going to suggest that, glad you figured it out by yourself.

**Comment by DotDebian** [comment]
There's finally some errors when using the * wildcard.
It occurs with a reason matching the regex and not matching too.

`[16:05:54 WARN]: Error dispatching event ServerKickEvent(cancelled=false, player=DotDebian, kickedFrom=BungeeServerInfo(name=faction, address=localhost/127.0.0.1:25566, restricted=false), kickReasonComponent=[TextComponent{text=» , BaseComponent(color=, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}, TextComponent{text=Le serveur sur lequel tu étais connecté a été fermé, tu as été reconnecté sur un serveur de secours., BaseComponent(color=, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}], cancelServer=BungeeServerInfo(name=login1, address=localhost/127.0.0.1:25567, restricted=false), state=CONNECTED, cause=EXCEPTION) to listener com.jaimemartz.playerbalancer.listeners.ServerKickListener@7d0100ea
java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*Sanction*
^
        at java.util.regex.Pattern.error(Pattern.java:1969) ~[?:1.8.0_252]
        at java.util.regex.Pattern.sequence(Pattern.java:2137) ~[?:1.8.0_252]
        at java.util.regex.Pattern.expr(Pattern.java:2010) ~[?:1.8.0_252]
        at java.util.regex.Pattern.compile(Pattern.java:1702) ~[?:1.8.0_252]
        at java.util.regex.Pattern.<init>(Pattern.java:1352) ~[?:1.8.0_252]
        at java.util.regex.Pattern.compile(Pattern.java:1028) ~[?:1.8.0_252]
        at java.util.regex.Pattern.matches(Pattern.java:1133) ~[?:1.8.0_252]
        at java.lang.String.matches(String.java:2121) ~[?:1.8.0_252]
        at com.jaimemartz.playerbalancer.listeners.ServerKickListener.onKick(ServerKickListener.java:41) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:46) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:437) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at net.md_5.bungee.connection.DownstreamBridge.exception(DownstreamBridge.java:87) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at net.md_5.bungee.netty.HandlerBoss.exceptionCaught(HandlerBoss.java:139) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:300) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:279) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:271) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:300) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:279) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.handleReadException(AbstractEpollStreamChannel.java:728) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:818) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

**Comment by jamezrin** [comment]
Try ```reasons=[".*Sanction.*"]```

**Comment by jamezrin** [comment]
Can you send me your config?

**Comment by DotDebian** [comment]
https://hasteb.in/ufowixac.coffeescript

I want my players to be fallbacked from faction server to lobbies, only if their kick reason doesn't match "*Sanction*" because it's a moderation kick/ban.

**Comment by jamezrin** [comment]
Enable `debug-info` and tell me what it says when someone gets kicked with that reason
